name: chat
description: Chat App
version: 2.0.0+2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.1
  image_picker: ^0.8.6+3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
